os: linux

language: python
sudo: enabled
python:
    - "3.6"
before_install:
    - openssl aes-256-cbc -K $encrypted_5d33e3994bfd_key -iv $encrypted_5d33e3994bfd_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
install:
    - pip install -r requirements.txt
script:
    - python scripts/dailyStats.py
